config/routes.rb
Rails.application.routes.draw do
  get 'movies', to: 'movies#index'
  get 'movies/new'
  post 'movies', to: 'movies#create'
  get 'movies/:id', to: 'movies#show', as: 'movie'
  get 'movies/:id/edit', to: 'movies#edit', as: 'edit_movie'
  patch 'movies/:id', to: 'movies#update'
  delete 'movies/:id', to: 'movies#destroy'
  post 'favorite_movies/:id', to: 'favorite_movies#create', as: 'favorite_movie'
  delete 'favorite_movies/:id', to: 'favorite_movies#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorite_movies_controller.rb
class FavoriteMoviesController < ApplicationController
  before_action :set_movie
  
  def create
    @movie.favorite = true
    @movie.save
    redirect_to movies_path, notice: 'Peli agregada a favoritos'
  end

  def destroy
    @movie.favorite = false
    @movie.save
    redirect_to movies_path, notice: 'Peli borrada de favoritos'
  end

  private
  def set_movie
    @movie = Movie.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  def index
    @regular_movies = Movie.where(favorite: false)
    @favorite_movies = Movie.where(favorite: true)
  end

  def new; end

  def create
    @movie = Movie.create (movie_params)
    redirect_to movies_path
  end

  def show; end

  def edit; end

  def update
    @movie.update(movie_params)
    redirect_to movies_path
  end

  def destroy
    @movie.delete
    redirect_to movies_path
  end

  private
  def movie_params
     params.require(:movie).permit(:name, :year)
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorite_movies_helper.rb
module FavoriteMoviesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Preparacion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |f| %>
  <%= f.label :name %> <br>
  <%= f.text_field :name %> <br> <br>

  <%= f.label :year %><br>
  <%= f.text_field :year %><br><br>

  <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>
<%= render "form", movie: @movie %><br>

<%= link_to "<<Atras", movies_path %>

app/views/movies/index.html.erb
<h1>Index Movies</h1>

<br>
<h2>Regular Movies</h2>
<% @regular_movies.each do |movie|%>
<p><%= "#{movie.name} / #{movie.year}" %>
   <%= link_to 'Ver', movie %>
   <%= link_to 'Editar', edit_movie_path(movie) %>
   <%= link_to 'Eliminar', movie, method: :delete, data: {confirm: 'Estas Seguro?'} %>
   <%= button_to "☆", favorite_movie_path(movie) %></p>
<% end %>

<br>
<h2>Favorites Movies</h2>
<% @favorite_movies.each do |movie|%>
<p><%= "#{movie.name} / #{movie.year}" %>
   <%= link_to 'Ver', movie %>
   <%= link_to 'Editar', edit_movie_path(movie) %>
   <%= link_to 'Eliminar', movie, method: :delete, data: {confirm: 'Estas Seguro?'} %>
   <%= button_to "★", favorite_movie_path(movie), method: :delete %></p>
<% end %>

<br>
<%= link_to "Crear Peli", movies_new_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>
<%= render "form", movie: Movie.new %>

app/views/movies/show.html.erb
<h1>Movie Show</h1>
<p><%= "#{@movie.name} / #{@movie.year}" %></p>

<%= link_to "<<Atras", movies_path %>